version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: capacity-planner-db-simple
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: capacity_planner
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile.simple
    container_name: capacity-planner-api-simple
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/capacity_planner
      PORT: 3000
    ports:
      - "3001:3000"
    volumes:
      - ./packages/assets-module/prisma:/app/packages/assets-module/prisma