[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm prisma:generate", "pnpm build:gateway:prod"]

[start]
cmd = "node dist/apps/api-gateway/main.js"